W8D1/reddit_clone_project/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html\
  resources :users, except:[:destroy] do
    resources :posts, only: [:edit, :update]
  end
  resources :posts, except: [:index, :edit, :update]
  resource :session, only:[:create, :new, :destroy]
  resources :subs, except: [:destroy] do
    resources :posts, only: [:index]
  end
end

W8D1/reddit_clone_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W8D1/reddit_clone_project/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  context    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
    validates :title, :sub_id, :author_id, presence: true

    belongs_to :sub,
        foreign_key: :sub_id,
        class_name: :Sub

    belongs_to :author,
        foreign_key: :author_id,
        class_name: :User

    has_many :post_subs,
        foreign_key: :post_id,
        class_name: :PostSub

    has_many :subs,
        through: :post_sub,
        source: :sub
end

W8D1/reddit_clone_project/app/models/post_sub.rb
class PostSub < ApplicationRecord
    validates :sub_id, :post_id, presence: true
    validates :post_id, uniqueness: {scope: :sub_id}

    belongs_to :sub,
        foreign_key: :sub_id,
        class_name: :Sub
    
    belongs_to :post,
        foreign_key: :post_id,
        class_name: :Post

    
end

W8D1/reddit_clone_project/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text             not null
#  moderator   :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Sub < ApplicationRecord
    validates :title, :description, :moderator, presence: true

    belongs_to :moderator,
        foreign_key: :moderator,
        class_name: :User

    has_many :posts,
        foreign_key: :sub_id,
        class_name: :Post

     has_many :post_subs,
        foreign_key: :sub_id,
        class_name: :PostSub
    
    has_many :sub_posts,
        through: :post_subs,
        source: :posts
end

W8D1/reddit_clone_project/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    validates :username, :password_digest, :session_token, presence: true
    validates :username, :session_token, uniqueness: true
    validates :password, length: {minimum: 6, allow_nil: true}

    attr_reader :password

    before_validation :ensure_session_token

    has_many :moderated_subs,
        foreign_key: :moderator,
        class_name: :Sub

    has_many :authored_posts,
        foreign_key: :author_id,
        class_name: :Post

    def self.find_by_credentials(username,password)
        user = User.find_by(username: username)
        if user && user.is_password?(password)
            user
        else
            nil
        end
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom.urlsafe_base64
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom.urlsafe_base64
    end
end

W8D1/reddit_clone_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :require_login, :logged_in?

    def current_user
        return nil unless session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def log_out
      current_user.reset_session_token!
      session[:session_token] = nil
      @current_user = nil
    end

    def logged_in?
      !!current_user
    end

    def require_login
      redirect_to new_session_url unless logged_in?
    end 
end

W8D1/reddit_clone_project/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.save
    flash[:errors] = @post.errors.full_messages
    redirect_to user_url(@post.author_id)
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      redirect_to user_url(@post.author_id)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy if current_user.id == post.author_id
    redirect_to users_url
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  # def index
  #   @posts = Post.where("sub_id = #{ params[:sub_id] }")
  #   @posts = Sub.find(params[:sub_id]).posts
  #   render :index
  # end

  def post_params
    params.require(:post).permit(:title, :url, :context, sub_ids: [])
  end
end

W8D1/reddit_clone_project/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_login, only: [:destroy]

  def new

  end

  def destroy
    log_out
  end 

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if user
      login!(user)
      redirect_to users_url
    else
      flash[:errors] = user.errors.full_messages
      render :new
    end
  end
end

W8D1/reddit_clone_project/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_mod, only: [:edit, :update]
  before_action :require_login

    def index
        @subs = Sub.all
        render :index
    end

    def create
        @sub = Sub.new(sub_params)
        @sub.moderator = current_user
        if @sub.save
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :new
        end
    end

    def new
        @sub = Sub.new
        render :new
    end

    def edit
        @sub = Sub.find(params[:id])
        render :edit
    end

    def show
        @sub = Sub.find(params[:id])
        render :show
    end

    def update
        @sub = Sub.find(params[:id])
        if @sub.update(sub_params)
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :edit
        end
    end

    def sub_params
        params.require(:sub).permit(:title, :description)
    end

    def require_mod
        sub = Sub.find_by(id: params[:id])
        redirect_to subs_url unless current_user.id == sub.moderator
    end
end

W8D1/reddit_clone_project/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to users_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
        redirect_to user_url(@user)
    else
        flash.now[:errors] = @user.errors.full_messages
        render :edit
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

W8D1/reddit_clone_project/app/helpers/application_helper.rb
module ApplicationHelper
end

W8D1/reddit_clone_project/app/helpers/posts_helper.rb
module PostsHelper
end

W8D1/reddit_clone_project/app/helpers/sessions_helper.rb
module SessionsHelper
end

W8D1/reddit_clone_project/app/helpers/subs_helper.rb
module SubsHelper
end

W8D1/reddit_clone_project/app/helpers/users_helper.rb
module UsersHelper
end

W8D1/reddit_clone_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditCloneProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if logged_in? %>
        <form action="<%= session_url%>" method="POST">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
          <input type="hidden" name="_method" value="DELETE">
          <button type="submit">Log Out</button>
        </form>        
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

W8D1/reddit_clone_project/app/views/posts/edit.html.erb
<h1>Edit <%= @post.title %></h1>

<form action="<%= post_url(@post) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title%>">
  </label>
  <label>URL
    <input type="text" name="post[url]" value="<%= @post.url%>">
  </label>
  <label>Context
    <input type="text" name="post[context]" value="<%= @post.context%>">
  </label>
  <label>Subs
    <% Sub.all.each do |sub| %>
      <label><%= sub.title %>
        <input type="checkbox" name="post[sub_id][]" value="<%= sub.id %>" <%= params[:post][:sub_id].include?(sub.id) ? checked : "" %>>
      </label>
    <% end %>
  </label>
  <button type="submit">Edit Post</button>
</form>

W8D1/reddit_clone_project/app/views/posts/new.html.erb
<h1>Create Title</h1>

<form action="<%= posts_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Title
    <input type="text" name="post[title]">
  </label>
  <label>URL
    <input type="text" name="post[url]">
  </label>
  <label>Context
    <input type="text" name="post[context]">
  </label>
  <label>Subs
    <% Sub.all.each do |sub| %>
      <label><%= sub.title %>
        <input type="checkbox" name="post[sub_id][]" value="<%= sub.id %>">
      </label>
    <% end %>
  </label>
  <button type="submit">Create Title</button>
</form>

W8D1/reddit_clone_project/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<div>
    <%= @post.url %>
</div>
<div>
    <%= @post.content %>
</div>

W8D1/reddit_clone_project/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>
<form action="<%= sub_url(@sub)%>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
    <label>Title
        <input type="text" name="sub[title]" value="<%= @sub.title%>">
    </label>
    <label>Description
        <input type="text" name="sub[description]" value="<%= @sub.description%>">
    </label>
    <button type="submit">Edit Sub</button>
</form>

W8D1/reddit_clone_project/app/views/subs/index.html.erb
<h1>All Subs</h1>

<% @subs.each do |sub| %>
  <a href="<%= sub_url(sub) %>">
    <%= sub.title %>
    <br>
  </a>
<% end %>

W8D1/reddit_clone_project/app/views/subs/new.html.erb
<h1>Create New Sub</h1>
<form action="<%= subs_url%>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
    <label>Title
        <input type="text" name="sub[title]" >
    </label>
    <label>Description
        <input type="text" name="sub[description]" >
    </label>
    <button type="submit">Create New Sub</button>
</form>

W8D1/reddit_clone_project/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<% @sub.posts.each do |post| %>
    <a href="<%=post_url(post)%>"><%= post.title %></a>
    <br>
    
<% end %>

W8D1/reddit_clone_project/app/views/users/edit.html.erb
<h1>Sign In to Reddit</h1>
<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
    <strong><%= error %></strong>
    <% end %>
<% end %>
<form action="<%= session_url %>" method="POST">
    
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
    <label>Username
        <input type="text" name="user[username]" value="<%= @user.username %>">
    </label>
    <label>Password
        <input type="password" name="user[password]">
    </label>
    <button type="submit">Sign In to Reddit</button>
</form>

W8D1/reddit_clone_project/app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
  <a href="<%= user_url(user) %>">
    <%= user.username %>
  </a>
<% end %>

W8D1/reddit_clone_project/app/views/users/new.html.erb
<h1>Sign Up for Reddit</h1>
<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
    <strong><%= error %></strong>
    <% end %>
<% end %>
<form action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
    <label>Username
        <input type="text" name="user[username]">
    </label>
    <label>Password
        <input type="password" name="user[password]">
    </label>
    <button type="submit">Sign Up for Reddit</button>
</form>

W8D1/reddit_clone_project/app/views/users/show.html.erb
<h1><%= @user.username %>'s Posts</h1>

<form action="<%= posts_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Title
    <input type="text" name="post[title]">
  </label>
  <label>URL
    <input type="text" name="post[url]">
  </label>
  <label>Context
    <input type="text" name="post[context]">
  </label>
  <label>Subs
    <% Sub.all.each do |sub| %>
      <label><%= sub.title %>
        <input type="checkbox" name="post[sub_id][]" value="<%= sub.id %>">
      </label>
    <% end %>
  </label>
  <button type="submit">Create Post</button>
</form>